services:
  - type: web
    name: snabb-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.main:app -c gunicorn.conf.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_BUCKET_NAME
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: STORAGE_PROVIDER
        value: "s3"
